[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    madhephaestus/ESP32Servo
    adafruit/Adafruit BNO055
    adafruit/Adafruit MCP9808 Library
    adafruit/Adafruit INA219
